//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeSuma.WsSuma {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTblPost", Namespace="http://google.org/", ItemName="tblPost")]
    [System.SerializableAttribute()]
    public class ArrayOfTblPost : System.Collections.Generic.List<ConsumeSuma.WsSuma.tblPost> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblPost", Namespace="http://google.org/")]
    [System.SerializableAttribute()]
    public partial class tblPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        private System.Nullable<System.DateTime> FechaField;
        
        private System.Nullable<int> ViewsField;
        
        private System.Nullable<int> LikesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Views {
            get {
                return this.ViewsField;
            }
            set {
                if ((this.ViewsField.Equals(value) != true)) {
                    this.ViewsField = value;
                    this.RaisePropertyChanged("Views");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Likes {
            get {
                return this.LikesField;
            }
            set {
                if ((this.LikesField.Equals(value) != true)) {
                    this.LikesField = value;
                    this.RaisePropertyChanged("Likes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://google.org/", ConfigurationName="WsSuma.MyWebServiciesSoap")]
    public interface MyWebServiciesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.org/Sumar", ReplyAction="*")]
        int Sumar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2);
        
        // CODEGEN: Generating message contract since element name getPostResult from namespace http://google.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://google.org/getPost", ReplyAction="*")]
        ConsumeSuma.WsSuma.getPostResponse getPost(ConsumeSuma.WsSuma.getPostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.org/getPost", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeSuma.WsSuma.getPostResponse> getPostAsync(ConsumeSuma.WsSuma.getPostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPost", Namespace="http://google.org/", Order=0)]
        public ConsumeSuma.WsSuma.getPostRequestBody Body;
        
        public getPostRequest() {
        }
        
        public getPostRequest(ConsumeSuma.WsSuma.getPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPostRequestBody {
        
        public getPostRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPostResponse", Namespace="http://google.org/", Order=0)]
        public ConsumeSuma.WsSuma.getPostResponseBody Body;
        
        public getPostResponse() {
        }
        
        public getPostResponse(ConsumeSuma.WsSuma.getPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://google.org/")]
    public partial class getPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumeSuma.WsSuma.ArrayOfTblPost getPostResult;
        
        public getPostResponseBody() {
        }
        
        public getPostResponseBody(ConsumeSuma.WsSuma.ArrayOfTblPost getPostResult) {
            this.getPostResult = getPostResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiciesSoapChannel : ConsumeSuma.WsSuma.MyWebServiciesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiciesSoapClient : System.ServiceModel.ClientBase<ConsumeSuma.WsSuma.MyWebServiciesSoap>, ConsumeSuma.WsSuma.MyWebServiciesSoap {
        
        public MyWebServiciesSoapClient() {
        }
        
        public MyWebServiciesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiciesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiciesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiciesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sumar(int num1, int num2) {
            return base.Channel.Sumar(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2) {
            return base.Channel.SumarAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeSuma.WsSuma.getPostResponse ConsumeSuma.WsSuma.MyWebServiciesSoap.getPost(ConsumeSuma.WsSuma.getPostRequest request) {
            return base.Channel.getPost(request);
        }
        
        public ConsumeSuma.WsSuma.ArrayOfTblPost getPost() {
            ConsumeSuma.WsSuma.getPostRequest inValue = new ConsumeSuma.WsSuma.getPostRequest();
            inValue.Body = new ConsumeSuma.WsSuma.getPostRequestBody();
            ConsumeSuma.WsSuma.getPostResponse retVal = ((ConsumeSuma.WsSuma.MyWebServiciesSoap)(this)).getPost(inValue);
            return retVal.Body.getPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeSuma.WsSuma.getPostResponse> ConsumeSuma.WsSuma.MyWebServiciesSoap.getPostAsync(ConsumeSuma.WsSuma.getPostRequest request) {
            return base.Channel.getPostAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeSuma.WsSuma.getPostResponse> getPostAsync() {
            ConsumeSuma.WsSuma.getPostRequest inValue = new ConsumeSuma.WsSuma.getPostRequest();
            inValue.Body = new ConsumeSuma.WsSuma.getPostRequestBody();
            return ((ConsumeSuma.WsSuma.MyWebServiciesSoap)(this)).getPostAsync(inValue);
        }
    }
}
